services:
  db:
    image: postgres:15
    container_name: todoapp-db
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: 2026ToDo!
      POSTGRES_DB: TodoApp
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: